-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgQMlil/EoSg8nlFo7
TzKdvhnRExRt3UwVmJyPmMPgZGegCgYIKoZIzj0DAQehRANCAAROHyiF+ktvv1SV
Y+68TFM3NWUuKbIMj4dPxjsTnsNg3LR+E3oHzgslZqZtoe5xi1ynDR/0o62Ys7Ml
RbWkMjC/
-----END PRIVATE KEY-----